steps:
 - id: install_packages
   name: 'node'
   entrypoint: 'npm'
   args: ['install']
 - id: build_angular
   name: 'node'
   entrypoint: 'npm'
   args: ['run', 'build']
   waitFor:
   - install_packages
 - id: install_packages
   name: 'node'
   entrypoint: 'npm'
   args: ['install']
   dir: functions
   waitFor:
   - build_angular
 - id: deploy_firebase
   name: 'gcr.io/pearbot-app/firebase'
   args: ['deploy']
   waitFor:
   - build_angular
